### ISSUE TITLE
Error when enabling HAProxyDetector v3.0.2 on spigot-1.21 server

### ISSUE THREAD

**Issue by Luoxiaohei2024** [andylizi/haproxy-detector#15] opened 2024-07-29 10:12 UTC
[18:07:42] [Server thread/INFO]: [ProtocolLib] Enabling ProtocolLib v5.3.0-SNAPSHOT-726
[18:07:42] [Server thread/INFO]: [HAProxyDetector] Enabling HAProxyDetector v3.0.2
[18:07:42] [Server thread/ERROR]: Error occurred while enabling HAProxyDetector v3.0.2 (Is it up to date?)
java.lang.NoClassDefFoundError: com/comphenix/protocol/injector/netty/ProtocolInjector
        at net.andylizi.haproxydetector.bukkit.BukkitMain.onEnable(BukkitMain.java:54) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:267) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:492) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_21_R1.CraftServer.enablePlugin(CraftServer.java:567) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4226-Spigot-146439e-2889b3a]
        at org.bukkit.craftbukkit.v1_21_R1.CraftServer.enablePlugins(CraftServer.java:481) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4226-Spigot-146439e-2889b3a]
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:237) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4226-Spigot-146439e-2889b3a]
        at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1017) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4226-Spigot-146439e-2889b3a]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4226-Spigot-146439e-2889b3a]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.ClassNotFoundException: com.comphenix.protocol.injector.netty.ProtocolInjector
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:160) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:112) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        ... 10 more

**Comment by andylizi** [comment] 2024-07-29 16:38
请尝试这个版本：https://github.com/andylizi/haproxy-detector/issues/3#issuecomment-1221897495

**Comment by andylizi** [comment] 2024-07-29 16:38
Duplicate of #3.

**Closed as not planned by andylizi** 2024-07-29 16:38 UTC
Labels: duplicate
